package nosurf

const (
	tokenLength = 32
)

/*
There are two types of tokens.

* The unmasked "real" token consists of 32 random bytes.
  It is stored in a cookie (base64-encoded) and it's the
  "reference" value that sent tokens get compared to.

* The masked "sent" token consists of 64 bytes:
  32 byte key used for one-time pad masking and
  32 byte "real" token masked with the said key.
  It is used as a value (base64-encoded as well)
  in forms and/or headers.

Upon processing, both tokens are base64-decoded
and then treated as 32/64 byte slices.
*/

// A token is generated by returning tokenLength bytes
// from crypto/rand
func generateToken() []byte { _ = "STUB: not implemented"; return nil }

func b64encode(data []byte) string { _ = "STUB: not implemented"; return "" }

func b64decode(data string) []byte { _ = "STUB: not implemented"; return nil }

// VerifyToken verifies the sent token equals the real one
// and returns a bool value indicating if tokens are equal.
// Supports masked tokens. realToken comes from Token(r) and
// sentToken is token sent unusual way.
func VerifyToken(realToken, sentToken string) bool { _ = "STUB: not implemented"; return false }

// verifyToken expects the realToken to be unmasked and the sentToken to be masked
func verifyToken(realToken, sentToken []byte) bool { _ = "STUB: not implemented"; return false }

// sentN == tokenLength means the token is unmasked
// sentN == 2*tokenLength means the token is masked.

// tokensEqual expects both tokens to be unmasked
func tokensEqual(realToken, sentToken []byte) bool { _ = "STUB: not implemented"; return false }

func checkForPRNG() {
	_ = "STUB: not implemented"
	// Check that cryptographically secure PRNG is available
	// In case it's not, panic.
	return
}

func init() {
	checkForPRNG()
}
